export type CrimeSeed = {
  slug: string;
  name: string;
  description: string;
  minRankOrder: number;
  successChance: number;
  cashMin: number;
  cashMax: number;
  expReward: number;
  energyCost: number;
  jailRiskChance: number;
  jailMinutes: number;
  cooldownSeconds: number;
};

/** Street crimes. Tuned so energy + cooldown gate rank speed; cash scales with risk. */
export const CRIMES: CrimeSeed[] = [
  {
    slug: "portemonnee",
    name: "Portemonnee stelen",
    description: "Licht iemand op straat op. Snel, vuil, en goed voor beginners.",
    minRankOrder: 1,
    successChance: 76,
    cashMin: 18,
    cashMax: 42,
    expReward: 6,
    energyCost: 6,
    jailRiskChance: 14,
    jailMinutes: 5,
    cooldownSeconds: 28,
  },
  {
    slug: "fiets",
    name: "Fiets stelen",
    description: "Een onbeheerde fiets bij het station. Klassiek Nederlands.",
    minRankOrder: 1,
    successChance: 70,
    cashMin: 28,
    cashMax: 72,
    expReward: 11,
    energyCost: 8,
    jailRiskChance: 18,
    jailMinutes: 8,
    cooldownSeconds: 32,
  },
  {
    slug: "pinautomaat",
    name: "Pinautomaat kraken",
    description: "Een nachtelijke skimmer en een boor. Klein geld, snel wegwezen.",
    minRankOrder: 2,
    successChance: 62,
    cashMin: 65,
    cashMax: 150,
    expReward: 20,
    energyCost: 12,
    jailRiskChance: 22,
    jailMinutes: 12,
    cooldownSeconds: 36,
  },
  {
    slug: "winkel",
    name: "Winkel overvallen",
    description: "Een avondwinkel met een dunne kassa en een nog dunnere beveiliging.",
    minRankOrder: 2,
    successChance: 60,
    cashMin: 85,
    cashMax: 200,
    expReward: 26,
    energyCost: 14,
    jailRiskChance: 26,
    jailMinutes: 14,
    cooldownSeconds: 40,
  },
  {
    slug: "inbraak",
    name: "Woninginbraak",
    description: "Wacht tot de lichten uitgaan. Sieraden, laptops, contant geld.",
    minRankOrder: 3,
    successChance: 52,
    cashMin: 150,
    cashMax: 350,
    expReward: 42,
    energyCost: 18,
    jailRiskChance: 30,
    jailMinutes: 20,
    cooldownSeconds: 45,
  },
  {
    slug: "koerier",
    name: "Drugskoerier",
    description: "Een tasje van A naar B. Vraag niet wat erin zit.",
    minRankOrder: 3,
    successChance: 48,
    cashMin: 200,
    cashMax: 470,
    expReward: 55,
    energyCost: 22,
    jailRiskChance: 34,
    jailMinutes: 28,
    cooldownSeconds: 50,
  },
  {
    slug: "container",
    name: "Havencontainer leeghalen",
    description: "Een zegel knippen in de nacht. Elektronica, sigaretten, of pech.",
    minRankOrder: 4,
    successChance: 38,
    cashMin: 340,
    cashMax: 780,
    expReward: 78,
    energyCost: 26,
    jailRiskChance: 36,
    jailMinutes: 36,
    cooldownSeconds: 55,
  },
  {
    slug: "juwelier",
    name: "Juwelier overvallen",
    description: "Hamers, vitrines en 90 seconden voordat de sirenes komen.",
    minRankOrder: 4,
    successChance: 40,
    cashMin: 400,
    cashMax: 880,
    expReward: 85,
    energyCost: 30,
    jailRiskChance: 38,
    jailMinutes: 40,
    cooldownSeconds: 58,
  },
  {
    slug: "afpersing",
    name: "Beschermingsgeld innen",
    description: "Een rondje langs de zaakjes. Respect kost, weigeren kost meer.",
    minRankOrder: 5,
    successChance: 36,
    cashMin: 620,
    cashMax: 1400,
    expReward: 115,
    energyCost: 34,
    jailRiskChance: 40,
    jailMinutes: 45,
    cooldownSeconds: 62,
  },
  {
    slug: "bankauto",
    name: "Bankauto beroven",
    description: "Twee man, een busje, en een route die je uit je hoofd kent.",
    minRankOrder: 5,
    successChance: 32,
    cashMin: 820,
    cashMax: 1850,
    expReward: 130,
    energyCost: 40,
    jailRiskChance: 44,
    jailMinutes: 55,
    cooldownSeconds: 70,
  },
  {
    slug: "casino",
    name: "Casino beroven",
    description: "Camera's, kooien en een kluis vol nachtelijk verlies.",
    minRankOrder: 6,
    successChance: 24,
    cashMin: 1550,
    cashMax: 3700,
    expReward: 210,
    energyCost: 52,
    jailRiskChance: 50,
    jailMinutes: 80,
    cooldownSeconds: 90,
  },
  {
    slug: "museum",
    name: "Museumroof",
    description: "Alarm, glas, en één schilderij dat de hele nacht waard is.",
    minRankOrder: 7,
    successChance: 20,
    cashMin: 2400,
    cashMax: 5400,
    expReward: 270,
    energyCost: 60,
    jailRiskChance: 52,
    jailMinutes: 100,
    cooldownSeconds: 95,
  },
  {
    slug: "transport",
    name: "Waardetransport",
    description: "Gepantserde deuren. Als het lukt, ben je weken zoet.",
    minRankOrder: 8,
    successChance: 16,
    cashMin: 4000,
    cashMax: 8600,
    expReward: 360,
    energyCost: 72,
    jailRiskChance: 56,
    jailMinutes: 120,
    cooldownSeconds: 110,
  },
  {
    slug: "arsenaal",
    name: "Legerarsenaal",
    description: "Een depot buiten de stad. Alleen voor wie het leger durft te krenken.",
    minRankOrder: 9,
    successChance: 13,
    cashMin: 7000,
    cashMax: 15500,
    expReward: 520,
    energyCost: 84,
    jailRiskChance: 60,
    jailMinutes: 150,
    cooldownSeconds: 125,
  },
  {
    slug: "parlement",
    name: "Ministerieel konvooi",
    description: "Alleen voor peetvaders. Eén fout en je verdwijnt jaren.",
    minRankOrder: 10,
    successChance: 11,
    cashMin: 10500,
    cashMax: 23000,
    expReward: 740,
    energyCost: 92,
    jailRiskChance: 64,
    jailMinutes: 200,
    cooldownSeconds: 160,
  },
];
