import {
  Banknote,
  Car,
  Cross,
  Dices,
  Dumbbell,
  Gavel,
  Home,
  LayoutDashboard,
  Mail,
  MessageSquare,
  Plane,
  Search,
  Shield,
  ShoppingBag,
  Skull,
  Store,
  Swords,
  UserCog,
  Users,
  VenetianMask,
} from "lucide-react";

export const NAV_ITEMS = [
  { href: "/game", label: "Overzicht", icon: LayoutDashboard },
  { href: "/game/misdaden", label: "Misdaden", icon: Skull },
  { href: "/game/vliegveld", label: "Vliegveld", icon: Plane },
  { href: "/game/hoeren", label: "Hoeren", icon: VenetianMask },
  { href: "/game/gym", label: "Gym", icon: Dumbbell },
  { href: "/game/casino", label: "Casino", icon: Dices },
  { href: "/game/auto-stelen", label: "Auto stelen", icon: Car },
  { href: "/game/garage", label: "Garage", icon: Home },
  { href: "/game/bank", label: "Bank", icon: Banknote },
  { href: "/game/winkel", label: "Winkel", icon: ShoppingBag },
  { href: "/game/markt", label: "Markt", icon: Store },
  { href: "/game/spelers", label: "Spelers", icon: Search },
  { href: "/game/familie", label: "Familie", icon: Users },
  { href: "/game/gevangenis", label: "Gevangenis", icon: Gavel },
  { href: "/game/ziekenhuis", label: "Ziekenhuis", icon: Cross },
  { href: "/game/berichten", label: "Berichten", icon: Mail },
  { href: "/game/logboek", label: "Logboek", icon: MessageSquare },
  { href: "/game/account", label: "Account", icon: UserCog },
] as const;

export const MOBILE_PRIMARY = [
  { href: "/game", label: "Home", icon: LayoutDashboard },
  { href: "/game/misdaden", label: "Misdaad", icon: Swords },
  { href: "/game/spelers", label: "PvP", icon: Shield },
  { href: "/game/berichten", label: "Post", icon: Mail },
] as const;

export const DASHBOARD_LINKS = [
  { href: "/game/misdaden", label: "Misdaden", hint: "Cash en exp op straat", icon: Skull },
  { href: "/game/vliegveld", label: "Vliegveld", hint: "Tien steden, smokkel", icon: Plane },
  { href: "/game/hoeren", label: "Hoeren", hint: "Ramen, crew en empire", icon: VenetianMask },
  { href: "/game/gym", label: "Gym", hint: "Kracht, conditie, vuisten", icon: Dumbbell },
  { href: "/game/casino", label: "Casino", hint: "Roulette, poker, de kooi", icon: Dices },
  { href: "/game/auto-stelen", label: "Auto stelen", hint: "Van Corsa tot Chiron", icon: Car },
  { href: "/game/bank", label: "Bank", hint: "Rente en een kluis", icon: Banknote },
  { href: "/game/winkel", label: "Winkel", hint: "Staal en kogels", icon: ShoppingBag },
] as const;
